global:
  scrape_interval: 5s

scrape_configs:
  - job_name: nginx-exporter
    static_configs:
      - targets: ['nginx-exporter:9113']
  - job_name: nginx-vts-exporter
    static_configs:
      - targets: ['web:8800']
